# Пример конфигурационного файла для проекта AST Create

# Настройки логирования
log:
  level: "INFO"  # Уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"  # Формат сообщений лога
  file: "logs/ast_create.log"  # Путь к файлу лога (null - только консоль)

# Настройки AI-агентов
agents:
  api_key: null  # API ключ для LLM сервиса (рекомендуется использовать переменную окружения)
  model: "gpt-4"  # Модель для использования
  max_tokens: 2000  # Максимальное количество токенов для запроса
  temperature: 0.7  # Температура генерации (креативность)

# Настройки грамматики
grammar:
  parser: "lalr"  # Тип парсера (lalr, earley)
  ambiguity: "resolve"  # Стратегия обработки неоднозначностей
  grammar_path: "ast_create/grammar/1c_base.lark"  # Путь к базовому файлу грамматики
  version_storage: "versions"  # Путь к хранилищу версий грамматики

# Общие настройки приложения
debug: false  # Режим отладки
max_file_size: 10485760  # Максимальный размер обрабатываемого файла в байтах (10 MB) 