name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      id: install-deps
      run: |
        python -m pip install --upgrade pip
        pip install 'crewai[tools]'
        pip install -e .
        pip install pytest pytest-cov pylint black isort
      # Добавляем повторные попытки при ошибке
      continue-on-error: true
      
    - name: Retry Install dependencies if needed
      if: ${{ steps.install-deps.outcome == 'failure' }}
      run: |
        python -m pip install --upgrade pip
        pip install crewai crewai-tools
        pip install -e .
        pip install pytest pytest-cov pylint black isort
    
    - name: Lint with pylint
      run: |
        pylint ast_create --fail-under=7.0
    
    - name: Check formatting with black
      run: |
        black --check ast_create
    
    - name: Check imports with isort
      run: |
        isort --check-only --profile black ast_create
    
    - name: Test with pytest
      run: |
        pytest --cov=ast_create tests/