name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade crewai-tools
        pip install -e .
        pip install pytest pytest-cov pylint black isort
    
    - name: Lint with pylint
      run: |
        pylint ast_create --fail-under=7.0
    
    - name: Check formatting with black
      run: |
        black --check ast_create
    
    - name: Check imports with isort
      run: |
        isort --check-only --profile black ast_create
    
    - name: Test with pytest
      run: |
        pytest --cov=ast_create tests/
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 